theme: minima
title: Austin's First Blog
author: AustinC9
email: austin.carson4@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: AustinC9

show_excerpts: true # set to false to remove excerpts on the homepage


